Add MacaronSwap Protocol
ByFishh/zk-flow pull request #27
Opened 2024-03-14 20:14 UTC by macaronchef

2024-03-17 16:44 UTC, ByFishh requested changes
Add the logo of your app in the public/protocols folder with the id provided (macaronswap.png)

2024-03-17 16:44 UTC, ByFishh commented on src/blockchains/zksync/protocols/macaronswap.ts
> +const addresses: string[] = [
You should lower the case of theses addresses otherwise the transactions will not match

2024-03-19 21:34 UTC, macaronchef commented
I added macaronswap logo to public folder. Please review again thanks.

2024-03-21 10:57 UTC, ByFishh approved these changes

2024-03-21 10:57 UTC, merged